import { Finding, Repository, HealthData, Report, UserProfile, Review } from "@/types";

export const MOCK_REPOSITORIES: Repository[] = [
  {
    id: "repo-1",
    name: "auth-service-python",
    description: "Core authentication and JWT token issuance microservice built with FastAPI and PostgreSQL.",
    primaryLanguage: "Python",
    healthScore: 84,
    openFindingsCount: 4,
    criticalFindingsCount: 1,
    lastReviewDate: "2026-08-03",
    branch: "main",
    fileCount: 42,
    updatedAt: "2 hours ago",
  },
  {
    id: "repo-2",
    name: "payment-gateway-api",
    description: "Stripe and PayPal webhook listener service with encryption keys management.",
    primaryLanguage: "Python",
    healthScore: 68,
    openFindingsCount: 9,
    criticalFindingsCount: 3,
    lastReviewDate: "2026-08-01",
    branch: "master",
    fileCount: 78,
    updatedAt: "1 day ago",
  },
  {
    id: "repo-3",
    name: "data-pipeline-worker",
    description: "Background ETL tasks parsing log files and transforming warehouse metrics.",
    primaryLanguage: "Python",
    healthScore: 92,
    openFindingsCount: 2,
    criticalFindingsCount: 0,
    lastReviewDate: "2026-07-28",
    branch: "main",
    fileCount: 31,
    updatedAt: "5 days ago",
  },
  {
    id: "repo-4",
    name: "ai-inference-engine",
    description: "PyTorch model loader and API wrapper serving real-time embedding requests.",
    primaryLanguage: "Python",
    healthScore: 76,
    openFindingsCount: 6,
    criticalFindingsCount: 1,
    lastReviewDate: "2026-07-25",
    branch: "feature/torch-v2",
    fileCount: 64,
    updatedAt: "1 week ago",
  },
];

export const MOCK_FINDINGS: Finding[] = [
  {
    id: "find-101",
    reviewId: "rev-2026-0803",
    repositoryId: "repo-1",
    title: "SQL Injection Risk in User Query Construction",
    summary: "Raw SQL string concatenation detected in repository database adapter module.",
    severity: "critical",
    confidence: 96,
    status: "open",
    file: "app/db/repositories/user_repo.py",
    line: 48,
    evidence: {
      codeSnippet: `query = f"SELECT * FROM users WHERE email = '{user_email}' AND status = 'ACTIVE'"` + "\n" + `cursor.execute(query)`,
      staticAnalysisSource: "Bandit",
      lineNumbers: "L47-L49",
    },
    aiExplanation: {
      problem: "Direct string interpolation into raw SQL queries creates a severe SQL Injection vulnerability (CWE-89). An attacker could bypass authentication by supplying `' OR '1'='1` in the `user_email` field.",
      whyItMatters: "Allows malicious actors to read, mutate, or drop user table records directly without proper authentication checks.",
      riskLevel: "High - Exposes user PII and database integrity.",
      bestPractice: "Always use parameterized queries or SQLAlchemy ORM bind parameters instead of raw string formatting.",
    },
    impact: "Potential unauthorized database access, privilege escalation, and data breach.",
    suggestedFix: {
      explanation: "Replace string interpolation with parameterized SQL query binding using standard tuple parameters.",
      patchPreview: `query = "SELECT * FROM users WHERE email = %s AND status = 'ACTIVE'"\ncursor.execute(query, (user_email,))`,
    },
    diff: {
      original: `- query = f"SELECT * FROM users WHERE email = '{user_email}' AND status = 'ACTIVE'"\n- cursor.execute(query)`,
      modified: `+ query = "SELECT * FROM users WHERE email = %s AND status = 'ACTIVE'"\n+ cursor.execute(query, (user_email,))`,
    },
    references: [
      "https://cwe.mitre.org/data/definitions/89.html",
      "https://bandit.readthedocs.io/en/latest/plugins/b608_hardcoded_sql_expressions.html",
    ],
  },
  {
    id: "find-102",
    reviewId: "rev-2026-0803",
    repositoryId: "repo-1",
    title: "Hardcoded Secret Token Constant",
    summary: "Hardcoded JWT secret key found in source configuration module.",
    severity: "high",
    confidence: 91,
    status: "open",
    file: "app/core/config.py",
    line: 19,
    evidence: {
      codeSnippet: `JWT_SECRET_KEY = "super_secret_production_key_12345!"`,
      staticAnalysisSource: "Bandit",
      lineNumbers: "L19",
    },
    aiExplanation: {
      problem: "Hardcoding sensitive cryptographic keys directly in code version control exposes secrets to anyone with repository read access (CWE-798).",
      whyItMatters: "Compromises JWT verification, enabling attackers to forge valid authentication signatures for any user.",
      riskLevel: "High - Cryptographic token forgery risk.",
      bestPractice: "Load secrets exclusively from environment variables or secure key vaults (e.g. AWS Secrets Manager or HashiCorp Vault).",
    },
    impact: "Enables unauthorized session impersonation across all API endpoints.",
    suggestedFix: {
      explanation: "Read `JWT_SECRET_KEY` dynamically from environment variables via `os.getenv` or Pydantic `BaseSettings`.",
      patchPreview: `import os\nJWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")`,
    },
    diff: {
      original: `- JWT_SECRET_KEY = "super_secret_production_key_12345!"`,
      modified: `+ import os\n+ JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")\n+ if not JWT_SECRET_KEY:\n+     raise ValueError("JWT_SECRET_KEY environment variable is missing")`,
    },
    references: [
      "https://cwe.mitre.org/data/definitions/798.html",
      "https://fastapi.tiangolo.com/advanced/settings/",
    ],
  },
  {
    id: "find-103",
    reviewId: "rev-2026-0803",
    repositoryId: "repo-1",
    title: "Unchecked Exception Handler in Async Middleware",
    summary: "Generic Exception catch block swallows runtime errors without logging context.",
    severity: "medium",
    confidence: 82,
    status: "open",
    file: "app/middleware/error_handler.py",
    line: 34,
    evidence: {
      codeSnippet: `try:\n    response = await call_next(request)\n    return response\nexcept Exception:\n    return JSONResponse(status_code=500, content={"message": "Error"})`,
      staticAnalysisSource: "Pylint",
      lineNumbers: "L31-L36",
    },
    aiExplanation: {
      problem: "Catching bare `Exception` without capturing stack trace or logging diagnostics masks underlying critical bugs like database disconnects or memory exhaustion.",
      whyItMatters: "Prevents Sentry/CloudWatch error tracking from receiving telemetry necessary for incident response.",
      riskLevel: "Medium - Degrades observability and debugging speed.",
      bestPractice: "Log the full exception trace using standard logging library before returning sanitized HTTP responses.",
    },
    impact: "Silent failures and difficult troubleshooting during system outages.",
    suggestedFix: {
      explanation: "Add structured logger call capturing `exc_info=True`.",
      patchPreview: `except Exception as exc:\n    logger.error(f"Unhandled middleware exception: {exc}", exc_info=True)\n    return JSONResponse(status_code=500, content={"message": "Internal Server Error"})`,
    },
    diff: {
      original: `- except Exception:\n-     return JSONResponse(status_code=500, content={"message": "Error"})`,
      modified: `+ except Exception as exc:\n+     logger.error("Unhandled API exception", exc_info=exc)\n+     return JSONResponse(status_code=500, content={"message": "Internal server error"})`,
    },
    references: [
      "https://docs.python.org/3/howto/logging.html",
    ],
  },
  {
    id: "find-104",
    reviewId: "rev-2026-0803",
    repositoryId: "repo-1",
    title: "Unused Import Statement",
    summary: "Unused module `hashlib` imported in password hashing utility.",
    severity: "low",
    confidence: 99,
    status: "open",
    file: "app/utils/security.py",
    line: 4,
    evidence: {
      codeSnippet: `import hashlib\nimport passlib`,
      staticAnalysisSource: "Pylint",
      lineNumbers: "L4",
    },
    aiExplanation: {
      problem: "Importing unused modules increases namespace clutter and minor load overhead.",
      whyItMatters: "Violates PEP 8 clean code guidelines.",
      riskLevel: "Low - Code hygiene only.",
      bestPractice: "Remove unused imports using automated tools like `autoflake` or `ruff`.",
    },
    impact: "Minor code maintainability noise.",
    suggestedFix: {
      explanation: "Delete unused import statement.",
      patchPreview: `import passlib`,
    },
    diff: {
      original: `- import hashlib\n  import passlib`,
      modified: `  import passlib`,
    },
    references: [
      "https://peps.python.org/pep-0008/#imports",
    ],
  },
];

export const MOCK_HEALTH_DATA: HealthData = {
  repositoryId: "repo-1",
  overallHealth: 84,
  qualityScore: 88,
  securityScore: 78,
  openFindings: 4,
  lastReviewDate: "2026-08-03",
  qualityTrend: [
    { date: "Jul 05", score: 72 },
    { date: "Jul 12", score: 75 },
    { date: "Jul 19", score: 79 },
    { date: "Jul 26", score: 81 },
    { date: "Aug 02", score: 84 },
  ],
  securityTrend: {
    critical: 1,
    high: 1,
    medium: 1,
    low: 1,
  },
  technicalDebt: {
    maintainability: "A (Low Debt)",
    complexity: "Cyclomatic Avg: 4.2",
    duplicatedCode: "1.4%",
    documentationCoverage: "92%",
  },
  weakModules: [
    {
      module: "app/db/repositories/user_repo.py",
      health: 62,
      findings: 2,
      risk: "High",
      lastReviewed: "2026-08-03",
    },
    {
      module: "app/core/config.py",
      health: 74,
      findings: 1,
      risk: "Medium",
      lastReviewed: "2026-08-03",
    },
    {
      module: "app/middleware/error_handler.py",
      health: 81,
      findings: 1,
      risk: "Medium",
      lastReviewed: "2026-08-03",
    },
  ],
  reviewMetrics: {
    averageReviewTime: "1.4s",
    totalReviews: 12,
    findingsResolved: 18,
    repositoryImprovement: "+12%",
  },
};

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-2026-0803",
    repositoryId: "repo-1",
    status: "completed",
    healthScore: 84,
    findingsCount: 4,
    createdAt: "2026-08-03 12:45",
    duration: "1.4s",
    reviewer: "BugZero AI v2.1",
  },
  {
    id: "rev-2026-0726",
    repositoryId: "repo-1",
    status: "completed",
    healthScore: 81,
    findingsCount: 6,
    createdAt: "2026-07-26 09:12",
    duration: "1.6s",
    reviewer: "BugZero AI v2.1",
  },
  {
    id: "rev-2026-0719",
    repositoryId: "repo-1",
    status: "completed",
    healthScore: 79,
    findingsCount: 8,
    createdAt: "2026-07-19 15:30",
    duration: "1.8s",
    reviewer: "BugZero AI v2.0",
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: "rep-001",
    reportName: "auth-service-python-security-audit.pdf",
    repositoryId: "repo-1",
    repositoryName: "auth-service-python",
    reviewDate: "2026-08-03",
    healthScore: 84,
    format: "PDF",
    sizeBytes: 1240000,
    downloadUrl: "#",
  },
  {
    id: "rep-002",
    reportName: "payment-gateway-findings.json",
    repositoryId: "repo-2",
    repositoryName: "payment-gateway-api",
    reviewDate: "2026-08-01",
    healthScore: 68,
    format: "JSON",
    sizeBytes: 450000,
    downloadUrl: "#",
  },
];

export const MOCK_USER: UserProfile = {
  id: "user-1",
  name: "Alex Vance",
  email: "alex.vance@engineering.io",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256",
  organization: "Antigravity Engineering",
  preferences: {
    defaultExplanationLevel: "Detailed",
    autoOpenDrawer: true,
    defaultReportFormat: "PDF",
    enableKeyboardShortcuts: true,
  },
  aiProvider: {
    provider: "OpenAI",
    model: "gpt-4o",
    explanationLevel: "Detailed",
  },
};
